# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: chriss.redirect::lang.redirect.category

# Model Form Field configuration
form: $/chriss/redirect/models/category/fields.yaml

# Model Class name
modelClass: ChrisS\Redirect\Models\Category

# Default redirect location
defaultRedirect: chriss/redirect/categories

# Create page
create:
    title: chriss.redirect::lang.title.create_category
    redirect: chriss/redirect/categories/update/:id
    redirectClose: chriss/redirect/categories

# Update page
update:
    title: chriss.redirect::lang.title.edit_category
    redirect: chriss/redirect/categories
    redirectClose: chriss/redirect/categories
