# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: chriss.redirect::lang.redirect.redirect

# Model Form Field configuration
form: $/chriss/redirect/models/redirect/fields.yaml

# Model Class name
modelClass: ChrisS\Redirect\Models\Redirect

# Default redirect location
defaultRedirect: chriss/redirect/redirects

# Create page
create:
    title: chriss.redirect::lang.title.create_redirect
    redirect: chriss/redirect/redirects/update/:id
    redirectClose: chriss/redirect/redirects

# Update page
update:
    title: chriss.redirect::lang.title.edit_redirect
    redirect: chriss/redirect/redirects
    redirectClose: chriss/redirect/redirects