# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: chriss.redirect::lang.title.import
    modelClass: ChrisS\Redirect\Models\RedirectImport
    list: $/chriss/redirect/models/redirectimport/columns.yaml
    redirect: chriss/redirect/redirects
export:
    title: chriss.redirect::lang.title.export
    modelClass: ChrisS\Redirect\Models\RedirectExport
    list: $/chriss/redirect/models/redirectexport/columns.yaml
    redirect: chriss/redirect/redirects
    filename: redirects.csv